revise backend engineer JD
bitmark-inc/jobs pull request #6
Opened 2021-04-26 08:13 UTC by nodestory

2021-04-26 08:25 UTC, nodestory commented on Backend Engineer.md
> +
I'm thinking if we should add more descriptions about our culture.

2021-04-26 08:25 UTC, nodestory commented on Backend Engineer.md
>  ## Profiles that are important to us
I'm thinking if we should add more descriptions about our culture.

2021-05-03 01:45 UTC, moskovich commented
Comments on job descriptions.

2021-05-03 01:46 UTC, moskovich requested changes
Try this.

2021-05-03 01:46 UTC, moskovich commented on Backend Engineer.md
> +> In the digital age, the ability to set rules around the usage and exchange of assets has become increasingly difficult for individuals. Crypto rights are programmable rules to control assets. They
Can you change this one to read:

"Bitmark Protocol is a system for organizing information about the world’s digital resources. People can activate — use, transfer, generate revenue from — resources safely with each other by verifying what a resource is and who controls it through Bitmark Protocol."

2021-05-03 01:46 UTC, moskovich commented on Backend Engineer.md
>  ## Profiles that are important to us
I don't think it's necessary. They should be able to understand our culture through our actions.

2021-05-03 04:17 UTC, merged